import { RouteGraph } from './actionTypes';

/**
 * Standard Wayanad NH-766 Corridor Graph
 */
export const WAYANAD_NH766_GRAPH: RouteGraph = {
  corridorName: 'NH-766 Kozhikode–Wayanad Mountain Pass',
  nodes: {
    S1: { lat: 11.4880, lng: 76.1220, name: 'Adivaram (Base Checkpoint)' },
    S5: { lat: 11.5000, lng: 75.9980, name: 'Lakkidi Viewpoint Curve' },
    S3: { lat: 11.5760, lng: 76.0980, name: 'Vythiri Ghat Section' },
    S2: { lat: 11.5480, lng: 76.2790, name: 'Meppadi Junction' },
    S6: { lat: 11.6090, lng: 76.0830, name: 'Kalpetta Bypass' },
    S4: { lat: 11.6280, lng: 76.4310, name: 'Muthanga Wildlife Corridor' },
  },
  edges: [
    {
      id: 'E_MAIN_NH766',
      fromSegmentId: 'S1',
      toSegmentId: 'S6',
      name: 'NH-766 Main Ghat Route via Lakkidi & Vythiri',
      routeRole: 'MAIN_ROUTE',
      distanceKm: 42.5,
      travelTimeMinutes: 65,
      hazards: [],
      roadState: {
        segmentId: 'S3',
        name: 'Vythiri Ghat Section',
        state: 'RESTRICTED',
        source: 'GSI Slope Bulletin',
        sourceType: 'MODELED',
        confidence: 0.85,
        lastUpdated: new Date().toISOString(),
      },
    },
    {
      id: 'E_ALT_A_KUTTIYADI',
      fromSegmentId: 'S1',
      toSegmentId: 'S6',
      name: 'Alternate Route A (via Kuttiyadi Ghats / Padinjarethara)',
      routeRole: 'ALTERNATE_A',
      distanceKm: 58.0,
      travelTimeMinutes: 90,
      hazards: [],
      roadState: {
        segmentId: 'S4',
        name: 'Muthanga / Padinjarethara Wildlife Sector',
        state: 'OPEN',
        source: 'Forest Dept Telemetry',
        sourceType: 'MODELED',
        confidence: 0.75,
        lastUpdated: new Date().toISOString(),
      },
    },
    {
      id: 'E_ALT_B_THAMARASSERY_BYPASS',
      fromSegmentId: 'S1',
      toSegmentId: 'S6',
      name: 'Alternate Route B (via Thamarassery Hill Bypass)',
      routeRole: 'ALTERNATE_B',
      distanceKm: 64.0,
      travelTimeMinutes: 105,
      hazards: [],
      roadState: {
        segmentId: 'S6',
        name: 'Kalpetta Southern Link',
        state: 'OPEN',
        source: 'PWD Road Advisory',
        sourceType: 'CROWD',
        confidence: 0.70,
        lastUpdated: new Date().toISOString(),
      },
    },
    {
      id: 'E_RETURN_ADIVARAM',
      fromSegmentId: 'S1',
      toSegmentId: 'S1',
      name: 'Return to Adivaram Plain Base',
      routeRole: 'RETURN_PATH',
      distanceKm: 6.0,
      travelTimeMinutes: 12,
      hazards: [],
      roadState: {
        segmentId: 'S1',
        name: 'Adivaram Plain Base',
        state: 'OPEN',
        source: 'Kerala Traffic Police',
        sourceType: 'AUTHORITATIVE',
        confidence: 0.95,
        lastUpdated: new Date().toISOString(),
      },
    },
  ],
  safeLocations: [
    {
      id: 'SAFE_ADIVARAM_BASE',
      name: 'Adivaram Rest & Rescue Staging Area (Base)',
      location: { lat: 11.4720, lng: 75.9890, name: 'Adivaram Foothill Center' },
      type: 'SAFE_ZONE',
      capacityStatus: 'AVAILABLE',
      distanceKm: 3.5,
      estimatedReachMinutes: 8,
      nearestSegmentId: 'S1',
    },
    {
      id: 'SAFE_LAKKIDI_SHELTER',
      name: 'Lakkidi Ghat Emergency Transit Station',
      location: { lat: 11.5120, lng: 76.0240, name: 'Lakkidi Ghat Shelter' },
      type: 'SHELTER',
      capacityStatus: 'AVAILABLE',
      distanceKm: 5.2,
      estimatedReachMinutes: 12,
      nearestSegmentId: 'S5',
    },
    {
      id: 'SAFE_VYTHIRI_CIVIL',
      name: 'Vythiri Community Center & First Aid Zone',
      location: { lat: 11.5540, lng: 76.0420, name: 'Vythiri Civil Zone' },
      type: 'SAFE_ZONE',
      capacityStatus: 'AVAILABLE',
      distanceKm: 8.0,
      estimatedReachMinutes: 18,
      nearestSegmentId: 'S3',
    },
  ],
};

/**
 * Signature Munnar → Valparai Multi-Hazard Corridor Graph (Hackathon Showcase)
 */
export const MUNNAR_VALPARAI_GRAPH: RouteGraph = {
  corridorName: 'Munnar–Valparai High Range Corridor (SH-17 / Tea Estate Pass)',
  nodes: {
    N_MUNNAR: { lat: 10.0889, lng: 77.0595, name: 'Munnar Town Center' },
    N_MATTUPETTY: { lat: 10.1050, lng: 77.1250, name: 'Mattupetty Pass' },
    N_GAP_ROAD: { lat: 10.0520, lng: 77.1420, name: 'Lockhart Gap Road' },
    N_CHINNAKANAL: { lat: 10.0340, lng: 77.1680, name: 'Chinnakanal Junction' },
    N_ANAMUDI_PASS: { lat: 10.2010, lng: 77.0120, name: 'Anamudi Shola Border' },
    N_SHOLAYAR: { lat: 10.2850, lng: 76.9420, name: 'Upper Sholayar Ridge' },
    N_VALPARAI: { lat: 10.3264, lng: 76.9554, name: 'Valparai Plateau Center' },
  },
  edges: [
    {
      id: 'E_MUNNAR_VALPARAI_MAIN',
      fromSegmentId: 'N_MUNNAR',
      toSegmentId: 'N_VALPARAI',
      name: 'Primary Route: Gap Road & Sholayar Mountain Pass',
      routeRole: 'MAIN_ROUTE',
      distanceKm: 68.0,
      travelTimeMinutes: 110,
      hazards: [],
      roadState: {
        segmentId: 'N_GAP_ROAD',
        name: 'Lockhart Gap Cliffside',
        state: 'RESTRICTED',
        source: 'GSI Slope Alert',
        sourceType: 'MODELED',
        confidence: 0.88,
        lastUpdated: new Date().toISOString(),
      },
    },
    {
      id: 'E_MUNNAR_VALPARAI_ALT_A',
      fromSegmentId: 'N_MUNNAR',
      toSegmentId: 'N_VALPARAI',
      name: 'Alternate Route A (via Chinnar / Anamudi Shola Reserve)',
      routeRole: 'ALTERNATE_A',
      distanceKm: 84.0,
      travelTimeMinutes: 135,
      hazards: [],
      roadState: {
        segmentId: 'N_ANAMUDI_PASS',
        name: 'Anamudi Wildlife Corridor',
        state: 'OPEN',
        source: 'Forest Wildlife Rapid Response',
        sourceType: 'MODELED',
        confidence: 0.82,
        lastUpdated: new Date().toISOString(),
      },
    },
    {
      id: 'E_MUNNAR_VALPARAI_ALT_B',
      fromSegmentId: 'N_MUNNAR',
      toSegmentId: 'N_VALPARAI',
      name: 'Alternate Route B (via Pollachi Plains Circuit)',
      routeRole: 'ALTERNATE_B',
      distanceKm: 112.0,
      travelTimeMinutes: 175,
      hazards: [],
      roadState: {
        segmentId: 'N_MATTUPETTY',
        name: 'Mattupetty Bypass Section',
        state: 'BLOCKED',
        source: 'State Highways Authority',
        sourceType: 'AUTHORITATIVE',
        confidence: 0.95,
        lastUpdated: new Date().toISOString(),
      },
    },
    {
      id: 'E_MUNNAR_RETURN',
      fromSegmentId: 'N_MUNNAR',
      toSegmentId: 'N_MUNNAR',
      name: 'Turn Back to Munnar Safe Town Base',
      routeRole: 'RETURN_PATH',
      distanceKm: 8.0,
      travelTimeMinutes: 15,
      hazards: [],
      roadState: {
        segmentId: 'N_MUNNAR',
        name: 'Munnar Town Valley',
        state: 'OPEN',
        source: 'District Administration',
        sourceType: 'AUTHORITATIVE',
        confidence: 0.95,
        lastUpdated: new Date().toISOString(),
      },
    },
  ],
  safeLocations: [
    {
      id: 'SAFE_MUNNAR_TOWN_ZONE',
      name: 'Munnar Town Civil Shelter & Rest Center',
      location: { lat: 10.0889, lng: 77.0595, name: 'Munnar Civil Center' },
      type: 'SAFE_ZONE',
      capacityStatus: 'AVAILABLE',
      distanceKm: 4.2,
      estimatedReachMinutes: 10,
      nearestSegmentId: 'N_MUNNAR',
    },
    {
      id: 'SAFE_LOCKHART_SHELTER',
      name: 'Lockhart Tea Estate Emergency Waystation',
      location: { lat: 10.0650, lng: 77.1120, name: 'Lockhart Estate Pavilion' },
      type: 'SHELTER',
      capacityStatus: 'AVAILABLE',
      distanceKm: 6.8,
      estimatedReachMinutes: 14,
      nearestSegmentId: 'N_GAP_ROAD',
    },
    {
      id: 'SAFE_MARAYOOR_FOREST_STATION',
      name: 'Marayoor Forest Aid & Protection Hub',
      location: { lat: 10.2740, lng: 77.1610, name: 'Marayoor Station' },
      type: 'SAFE_ZONE',
      capacityStatus: 'AVAILABLE',
      distanceKm: 16.0,
      estimatedReachMinutes: 28,
      nearestSegmentId: 'N_ANAMUDI_PASS',
    },
  ],
};
