import { ResolveActionParams } from './actionTypes';

export interface DemoScenario {
  id: string;
  name: string;
  badge: string;
  corridor: 'WAYANAD_NH766' | 'MUNNAR_VALPARAI';
  description: string;
  narrativeTime: string;
  params: ResolveActionParams;
}

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'SCENARIO_1_NORMAL',
    name: 'Scenario 1: Normal Travel Conditions',
    badge: 'Baseline',
    corridor: 'WAYANAD_NH766',
    description: 'Clear weather, nominal slope stability across NH-766 ghat curves, standard transit.',
    narrativeTime: '08:30 AM',
    params: {
      corridorType: 'WAYANAD_NH766',
      baseConfidence: 0.85,
      isSimulatedScenario: true,
      scenarioName: 'Normal Travel Conditions',
      travelerState: {
        travelMode: 'Car',
        speedKmh: 40,
        currentSegmentId: 'S1',
      },
      hazards: [
        {
          id: 'H_NORM_1',
          type: 'HEAVY_RAIN',
          location: { lat: 11.4880, lng: 76.1220, name: 'Adivaram' },
          affectedSegments: ['S1'],
          severity: 0.15,
          confidence: 0.85,
          trend: 'stable',
          source: 'IMD Wayanad Radar',
          sourceType: 'MODELED',
          lastUpdated: new Date().toISOString(),
        },
      ],
      roadStates: [
        {
          segmentId: 'S1',
          name: 'Adivaram Foothills',
          state: 'OPEN',
          source: 'Kerala Traffic Police',
          sourceType: 'AUTHORITATIVE',
          confidence: 0.95,
          lastUpdated: new Date().toISOString(),
        },
        {
          segmentId: 'S3',
          name: 'Vythiri Ghat Pass',
          state: 'OPEN',
          source: 'PWD Highway Div',
          sourceType: 'AUTHORITATIVE',
          confidence: 0.90,
          lastUpdated: new Date().toISOString(),
        },
      ],
    },
  },
  {
    id: 'SCENARIO_2_RAIN_ESCALATION',
    name: 'Scenario 2: Heavy Rainfall Escalation',
    badge: 'Caution',
    corridor: 'WAYANAD_NH766',
    description: 'Intense rain bands develop along the ghat pass; surface runoff and reduced tire traction detected.',
    narrativeTime: '08:45 AM',
    params: {
      corridorType: 'WAYANAD_NH766',
      baseConfidence: 0.82,
      isSimulatedScenario: true,
      scenarioName: 'Heavy Rainfall Escalation',
      travelerState: {
        travelMode: 'Car',
        speedKmh: 35,
        currentSegmentId: 'S5',
      },
      hazards: [
        {
          id: 'H_RAIN_1',
          type: 'HEAVY_RAIN',
          location: { lat: 11.5000, lng: 75.9980, name: 'Lakkidi Ghat Curve' },
          affectedSegments: ['S5', 'S3'],
          severity: 0.48,
          confidence: 0.82,
          trend: 'rising',
          source: 'IMD Doppler Radar & Automatic Weather Station',
          sourceType: 'MODELED',
          lastUpdated: new Date().toISOString(),
        },
      ],
    },
  },
  {
    id: 'SCENARIO_3_SIGNATURE_CONFLICT',
    name: 'Scenario 3: Signature Multi-Hazard Conflict (Landslide + Wildlife + Road Blockage)',
    badge: 'Signature Hackathon Demo',
    corridor: 'MUNNAR_VALPARAI',
    description: 'Primary route has rising Landslide risk (0.85); Alternate A intersects active Wildlife pass; Alternate B is structurally Closed. Safe Shelter is available.',
    narrativeTime: '09:00 AM',
    params: {
      corridorType: 'MUNNAR_VALPARAI',
      baseConfidence: 0.88,
      isSimulatedScenario: true,
      scenarioName: 'Signature Multi-Hazard Conflict',
      travelerState: {
        travelMode: 'Car',
        speedKmh: 30,
        currentSegmentId: 'N_GAP_ROAD',
      },
      hazards: [
        {
          id: 'H_LANDSLIDE_MAIN',
          type: 'LANDSLIDE',
          location: { lat: 10.0520, lng: 77.1420, name: 'Lockhart Gap Cliffside (Main Route)' },
          affectedSegments: ['N_GAP_ROAD', 'N_SHOLAYAR'],
          severity: 0.85,
          confidence: 0.90,
          trend: 'rising',
          source: 'GSI Slope InSAR Telemetry',
          sourceType: 'MODELED',
          lastUpdated: new Date().toISOString(),
        },
        {
          id: 'H_WILDLIFE_ALT_A',
          type: 'WILDLIFE',
          location: { lat: 10.2010, lng: 77.0120, name: 'Anamudi Shola Reserve (Alternate A)' },
          affectedSegments: ['N_ANAMUDI_PASS'],
          severity: 0.65,
          confidence: 0.85,
          trend: 'rising',
          source: 'Forest Wildlife Rapid Response Sensor Grid',
          sourceType: 'MODELED',
          lastUpdated: new Date().toISOString(),
        },
        {
          id: 'H_CLOSURE_ALT_B',
          type: 'ROAD_CLOSURE',
          location: { lat: 10.1050, lng: 77.1250, name: 'Mattupetty Bridge Bypass (Alternate B)' },
          affectedSegments: ['N_MATTUPETTY'],
          severity: 0.90,
          confidence: 0.95,
          trend: 'stable',
          source: 'State Highways Emergency Directive',
          sourceType: 'AUTHORITATIVE',
          lastUpdated: new Date().toISOString(),
        },
      ],
      roadStates: [
        {
          segmentId: 'N_GAP_ROAD',
          name: 'Lockhart Gap Road',
          state: 'RESTRICTED',
          source: 'Highways Patrol',
          sourceType: 'AUTHORITATIVE',
          confidence: 0.92,
          lastUpdated: new Date().toISOString(),
        },
        {
          segmentId: 'N_MATTUPETTY',
          name: 'Mattupetty Bypass Section',
          state: 'BLOCKED',
          source: 'PWD Road Advisory',
          sourceType: 'AUTHORITATIVE',
          confidence: 0.95,
          lastUpdated: new Date().toISOString(),
        },
      ],
    },
  },
  {
    id: 'SCENARIO_4_RECOVERY_DIVERT',
    name: 'Scenario 4: Dynamic Re-Evaluation & Safe Recovery (Detour Clears)',
    badge: 'Dynamic Transition',
    corridor: 'MUNNAR_VALPARAI',
    description: 'Simulated time advances 25 minutes: Wildlife movement subsides on Alternate A. Engine automatically clears and recommends Detour A.',
    narrativeTime: '09:25 AM',
    params: {
      corridorType: 'MUNNAR_VALPARAI',
      baseConfidence: 0.85,
      isSimulatedScenario: true,
      scenarioName: 'Dynamic Recovery: Detour A Cleared',
      travelerState: {
        travelMode: 'Car',
        speedKmh: 35,
        currentSegmentId: 'N_MUNNAR',
      },
      hazards: [
        {
          id: 'H_LANDSLIDE_MAIN',
          type: 'LANDSLIDE',
          location: { lat: 10.0520, lng: 77.1420, name: 'Lockhart Gap Cliffside (Main Route)' },
          affectedSegments: ['N_GAP_ROAD'],
          severity: 0.80,
          confidence: 0.88,
          trend: 'stable',
          source: 'GSI Slope InSAR Telemetry',
          sourceType: 'MODELED',
          lastUpdated: new Date().toISOString(),
        },
        {
          id: 'H_WILDLIFE_ALT_A',
          type: 'WILDLIFE',
          location: { lat: 10.2010, lng: 77.0120, name: 'Anamudi Shola Reserve' },
          affectedSegments: ['N_ANAMUDI_PASS'],
          severity: 0.15,
          confidence: 0.80,
          trend: 'falling',
          source: 'Forest Wildlife Ranger Patrol',
          sourceType: 'MODELED',
          lastUpdated: new Date().toISOString(),
        },
      ],
      roadStates: [
        {
          segmentId: 'N_ANAMUDI_PASS',
          name: 'Anamudi Forest Pass',
          state: 'OPEN',
          source: 'Forest Dept Checkpost',
          sourceType: 'AUTHORITATIVE',
          confidence: 0.90,
          lastUpdated: new Date().toISOString(),
        },
      ],
    },
  },
  {
    id: 'SCENARIO_5_OFFLINE_DECAY',
    name: 'Scenario 5: Ghat Dead Zone Confidence Decay',
    badge: 'Offline Integrity',
    corridor: 'WAYANAD_NH766',
    description: 'Simulated 150 minutes in mountain dead zone. Confidence decays below safe 40% threshold -> INSUFFICIENT_DATA with SDMA helpline.',
    narrativeTime: '11:00 AM',
    params: {
      corridorType: 'WAYANAD_NH766',
      baseConfidence: 0.32,
      isSimulatedScenario: true,
      scenarioName: 'Offline Dead Zone Decay',
      travelerState: {
        travelMode: 'Car',
        speedKmh: 20,
        currentSegmentId: 'S3',
      },
      hazards: [],
    },
  },
];
